# Generated by Django 6.0.6 on 2026-07-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=200)),
                ('banco', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
